---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.69.2/hugo_0.69.2_Linux-64bit.deb
  - sudo dpkg -i hugo_0.69.2_Linux-64bit.deb
branches:
  only:
    - website-source
script:
  - ./build.sh
deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: website-source
